/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import ButonView.Chambres;
import ButonView.Clients;
import java.sql.*;
import javax.swing.JOptionPane;
import static DataBase.ConnectionBd.*;
import MainpageJava.MyMenu;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import utilisateurs.utilisateurs;

/**
 *
 * @author prince
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    /*
    Variables static du package mysql , pour pouvoir les utiliser dans les autres classes 
     */
    PreparedStatement pst;
    ResultSet rs;

    public Login() {
        initComponents();
        Connect();
        //this.setResizable(false);
        txtmdp.setEchoChar((char) 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtmdp = new javax.swing.JPasswordField();
        Connection = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtposte = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 137, 143));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hôtel LE PRINCE");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 310, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/userpassword_deusuari_787 (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 190, 140));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/avatardefault_92824 (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, 60));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/preferencesdesktopuserpassword_94510 (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 50, 50));

        txtnom.setFont(new java.awt.Font("Noto Serif CJK HK Black", 2, 14)); // NOI18N
        txtnom.setForeground(new java.awt.Color(153, 153, 153));
        txtnom.setText("Username");
        txtnom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomFocusLost(evt);
            }
        });
        txtnom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtnomMouseEntered(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomKeyPressed(evt);
            }
        });
        jPanel1.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 260, 40));

        txtmdp.setFont(new java.awt.Font("Noto Serif CJK KR Black", 2, 14)); // NOI18N
        txtmdp.setForeground(new java.awt.Color(153, 153, 153));
        txtmdp.setText("password");
        txtmdp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmdpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmdpFocusLost(evt);
            }
        });
        txtmdp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmdpKeyPressed(evt);
            }
        });
        jPanel1.add(txtmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 260, 40));

        Connection.setBackground(new java.awt.Color(144, 159, 137));
        Connection.setFont(new java.awt.Font("P052", 1, 18)); // NOI18N
        Connection.setForeground(new java.awt.Color(153, 16, 103));
        Connection.setText("SE CONNECTER");
        Connection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionActionPerformed(evt);
            }
        });
        jPanel1.add(Connection, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 320, 50));

        jCheckBox1.setFont(new java.awt.Font("C059", 0, 14)); // NOI18N
        jCheckBox1.setText("Afficher le mot de passe");
        jCheckBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox1.setHideActionText(true);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 200, 30));

        jLabel5.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("S'INSCRIRE ?");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 100, 30));

        txtposte.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        txtposte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Réceptionniste", "Personnel Bar", "Personnel Restaurant", "Administrateur", " " }));
        jPanel1.add(txtposte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 260, 40));

        jLabel6.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel6.setText("Poste");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 60, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("/home/prince/Téléchargements/delete_delete_exit_1577.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 580));

        setSize(new java.awt.Dimension(565, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionActionPerformed
        // TODO add your handling code here:

        try {

            Connect();
            pst = con.prepareStatement("SELECT * FROM utilisateurs WHERE nom_utilisateur = ? and mot_de_passe = ? and poste = ?;");
            pst.setString(1, txtnom.getText());
            pst.setString(2, txtmdp.getText());
            pst.setString(3, txtposte.getSelectedItem().toString());
            rs = pst.executeQuery();
            Clients cl = new Clients();
            // Condition pour se connecter
            if (rs.next()) {
                String poste = rs.getString("poste");
                if (poste.contains("Administrateur")) {
                    Login.super.dispose();
                    MyMenu m = new MyMenu();// instance de la classe menu pour afficher la fenêtre Menu
                    m.btnutilisateur.hide();
                    m.setVisible(true);
                } else if (poste.contains("Réceptionniste")) {
                    Login.super.dispose();
                    MyMenu m = new MyMenu();// instance de la classe menu pour afficher la fenêtre Menu
                    m.btnutilisateur.hide();
                    m.btnservice.setEnabled(false);
                    m.btnconsommation.setEnabled(false);
                    m.setVisible(true);
                    //Chambres.AddRoom.enable(false);
                } else if (poste.contains("Personnel Bar")) {
                    Login.super.dispose();
                    MyMenu m = new MyMenu();// instance de la classe menu pour afficher la fenêtre Menu
                    m.btnutilisateur.hide();
                    m.btnchambre.setEnabled(false);
                    m.btnreservation.setEnabled(false);
                    cl.AddCustomer.hide();
                    cl.ModifyCustomer.hide();
                    cl.DeleteCustomer.hide();
                    cl.RESET.hide();
                    m.setVisible(true);
                    if (m.btnclient.isSelected()) {
                        cl.AddCustomer.hide();
                        cl.ModifyCustomer.hide();
                        cl.DeleteCustomer.hide();
                        cl.RESET.hide();
                    }
                } else if (poste.contains("Personnel Restaurant")) {
                    Login.super.dispose();
                    MyMenu m = new MyMenu();// instance de la classe menu pour afficher la fenêtre Menu
                    m.btnutilisateur.hide();
                    m.btnutilisateur.hide();
                    m.btnchambre.hide();
                    m.btnreservation.setEnabled(false);
                    cl.AddCustomer.hide();
                    cl.ModifyCustomer.hide();
                    cl.DeleteCustomer.hide();
                    cl.RESET.hide();
                    m.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, " Erreur de connection ! \n Veuillez vérifier votre mot de passe ou nom d'utilisateur");
            }
            pst.close();
            con.close();// Se déconnecter de la base données !

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Connection echouée !!! " + e.getMessage());
        }
    }//GEN-LAST:event_ConnectionActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            txtmdp.setEchoChar((char) 0);
        } else {
            txtmdp.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtnomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomFocusGained
        // TODO add your handling code here:
        if (txtnom.getText().equals("Username")) {
            txtnom.setText("");
            txtnom.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtnomFocusGained

    private void txtnomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomFocusLost
        // TODO add your handling code here:
        if (txtnom.getText().equals("")) {
            txtnom.setText("Username");
            txtnom.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnomFocusLost

    private void txtmdpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmdpFocusGained
        // TODO add your handling code here:
        //txtmdp.setEchoChar('*');
        if (txtmdp.getText().length() == 8) {
            txtmdp.setText("");
            txtmdp.setEchoChar('*');
            txtmdp.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtmdpFocusGained

    private void txtmdpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmdpFocusLost
        // TODO add your handling code here:
        if (txtmdp.getText().equals("")) {
            txtmdp.setText("Password");
            if (txtmdp.getText().equals("Password")) {
                txtmdp.setEchoChar((char) 0);
            }
            txtmdp.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtmdpFocusLost

    private void txtnomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnomMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomMouseEntered

    private void txtnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtmdp.requestFocus();

        }
        /*
            Si l'utilisateur appuie sur la touche Entrée dans le champ de texte textField1,
            la méthode requestFocus() est appelée sur le champ de texte textField2. 
            Cela déplace le curseur sur le champ de texte textField2.
         */
    }//GEN-LAST:event_txtnomKeyPressed

    private void txtmdpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmdpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ConnectionActionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, null));

        }
    }//GEN-LAST:event_txtmdpKeyPressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        // TODO add your handling code here:
        utilisateurs ut = new utilisateurs();
        Login.super.dispose();
        ut.setVisible(true);
        ut.AddUser.setText("Envoyer");
        ut.deleteUser.hide();
        ut.updateUser.hide();
        ut.jTable1.hide();
        ut.research.hide();
        ut.jLabel8research.hide();
        ut.btnmenu.hide();
        
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Connection;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtmdp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JComboBox<String> txtposte;
    // End of variables declaration//GEN-END:variables
}
