/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ButonView;

import static DataBase.ConnectionBd.*;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import service.Consommaton;

/**
 *
 * @author prince
 */
public class Consommations extends javax.swing.JInternalFrame {

    ResultSet rs;
    PreparedStatement ps;

    /**
     * Creates new form Consommations
     */
    public Consommations() {
        initComponents();
        Connect();
        TableCommandeBoisson();
        TablePlatCommande();
        remove_title_bar();
        coloumnWidth();
        coloumnWidth2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void remove_title_bar() {
        putClientProperty("Clients.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }

    public void coloumnWidth() {
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(18);
        columnModel.getColumn(1).setPreferredWidth(21);
        columnModel.getColumn(2).setPreferredWidth(70);
        columnModel.getColumn(3).setPreferredWidth(22);
        columnModel.getColumn(4).setPreferredWidth(81);
        columnModel.getColumn(5).setPreferredWidth(40);
        columnModel.getColumn(6).setPreferredWidth(50);
    }

    public void coloumnWidth2() {
        TableColumnModel columnModel = jTable2.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(18);
        columnModel.getColumn(1).setPreferredWidth(21);
        columnModel.getColumn(2).setPreferredWidth(70);
        columnModel.getColumn(3).setPreferredWidth(22);
        columnModel.getColumn(4).setPreferredWidth(81);
        columnModel.getColumn(5).setPreferredWidth(40);
        columnModel.getColumn(6).setPreferredWidth(50);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtclienID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBoissonLibelle = new javax.swing.JTextField();
        txtquantiteboisson = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Deletedrunk = new javax.swing.JButton();
        AddDrunk = new javax.swing.JButton();
        printAddition = new javax.swing.JButton();
        Updatedrunk = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtcategorie = new javax.swing.JComboBox<>();
        totacmdDrunk = new javax.swing.JButton();
        txtTotalDrunk = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtdateCommande = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txtnomclient = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtboissonID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPU = new javax.swing.JTextField();
        ResetCommand = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtcmdDrunk = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_id_plat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_LibellePlat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_PrixPlat = new javax.swing.JTextField();
        calculerTotalprixPlat = new javax.swing.JButton();
        resetcommandPlat = new javax.swing.JButton();
        Addcom_plat = new javax.swing.JButton();
        UpdatecommandePlat = new javax.swing.JButton();
        DeletecommandePlat = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_TypePlat = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_nom_cli_plat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_total_prix_plat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtid_cli_plat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_datecommandeplat = new com.toedter.calendar.JDateChooser();
        txt_quantite_plat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        searchfood = new javax.swing.JTextField();

        jTabbedPane1.setFont(new java.awt.Font("C059", 0, 18)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("URW Bookman", 0, 16)); // NOI18N
        jLabel1.setText("Matricule_Client");

        txtclienID.setFont(new java.awt.Font("P052", 0, 18)); // NOI18N
        txtclienID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclienIDActionPerformed(evt);
            }
        });
        txtclienID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtclienIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtclienIDKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("URW Bookman", 0, 16)); // NOI18N
        jLabel2.setText("Catégorie");

        txtBoissonLibelle.setFont(new java.awt.Font("P052", 0, 18)); // NOI18N
        txtBoissonLibelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoissonLibelleActionPerformed(evt);
            }
        });
        txtBoissonLibelle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBoissonLibelleKeyPressed(evt);
            }
        });

        txtquantiteboisson.setFont(new java.awt.Font("P052", 0, 18)); // NOI18N
        txtquantiteboisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantiteboissonActionPerformed(evt);
            }
        });
        txtquantiteboisson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtquantiteboissonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtquantiteboissonKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("URW Bookman", 0, 16)); // NOI18N
        jLabel3.setText("Quantité");

        Deletedrunk.setFont(new java.awt.Font("P052", 0, 15)); // NOI18N
        Deletedrunk.setText("Supprimer");
        Deletedrunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletedrunkActionPerformed(evt);
            }
        });

        AddDrunk.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        AddDrunk.setText("Ajouter à l'addition");
        AddDrunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDrunkActionPerformed(evt);
            }
        });

        printAddition.setFont(new java.awt.Font("P052", 0, 15)); // NOI18N
        printAddition.setText("Imprimer l'addition");
        printAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printAdditionActionPerformed(evt);
            }
        });

        Updatedrunk.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        Updatedrunk.setText("Modifier");
        Updatedrunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatedrunkActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("P052", 0, 16)); // NOI18N
        jLabel11.setText("Libellé_Boisson");

        txtcategorie.setFont(new java.awt.Font("P052", 0, 18)); // NOI18N
        txtcategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vin", "Liqueur", "Bière", "Whisky" }));

        totacmdDrunk.setFont(new java.awt.Font("P052", 0, 16)); // NOI18N
        totacmdDrunk.setText("Calculer total");
        totacmdDrunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totacmdDrunkActionPerformed(evt);
            }
        });

        txtTotalDrunk.setEditable(false);
        txtTotalDrunk.setFont(new java.awt.Font("P052", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("P052", 0, 16)); // NOI18N
        jLabel14.setText("Date");

        txtdateCommande.setDateFormatString("dd/MM/yyyy");
        txtdateCommande.setFont(new java.awt.Font("P052", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("URW Bookman", 0, 16)); // NOI18N
        jLabel15.setText("Nom Client");

        txtnomclient.setFont(new java.awt.Font("P052", 0, 18)); // NOI18N
        txtnomclient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomclientKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("URW Bookman", 0, 16)); // NOI18N
        jLabel16.setText("ID-Boisson");

        txtboissonID.setFont(new java.awt.Font("P052", 0, 18)); // NOI18N
        txtboissonID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtboissonIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtboissonIDKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("URW Bookman", 0, 16)); // NOI18N
        jLabel7.setText("Prix Unitaire");

        txtPU.setEditable(false);
        txtPU.setFont(new java.awt.Font("P052", 0, 18)); // NOI18N

        ResetCommand.setFont(new java.awt.Font("P052", 0, 15)); // NOI18N
        ResetCommand.setText("Reset");
        ResetCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetCommandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(totacmdDrunk)
                .addGap(20, 20, 20)
                .addComponent(txtTotalDrunk, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(AddDrunk)
                .addGap(6, 6, 6)
                .addComponent(Updatedrunk, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(printAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Deletedrunk)
                .addGap(6, 6, 6)
                .addComponent(ResetCommand))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtclienID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnomclient, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtboissonID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtcategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBoissonLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtdateCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPU, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtquantiteboisson, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtclienID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnomclient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtboissonID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBoissonLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdateCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPU, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtquantiteboisson, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totacmdDrunk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtTotalDrunk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddDrunk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updatedrunk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletedrunk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 580));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 102));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 660, 210));

        jLabel4.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/service/IMAGE/analysis_analytics_magnifier_search_locate_magnifyng_glass_icon_153884.png"))); // NOI18N
        jLabel4.setText("RECHERCHER");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 171, -1));

        jButton1.setFont(new java.awt.Font("URW Bookman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setIcon(new javax.swing.ImageIcon("/home/prince/Téléchargements/3925426-print-printer-printing-icon_111556.png")); // NOI18N
        jButton1.setText("Print");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 136, 54));

        txtcmdDrunk.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtcmdDrunk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcmdDrunkKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcmdDrunkKeyReleased(evt);
            }
        });
        jPanel1.add(txtcmdDrunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 271, 36));

        jTabbedPane1.addTab("Commande de Boissons", jPanel1);

        jPanel2.setFont(new java.awt.Font("Noto Serif CJK TC Black", 0, 14)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel5.setText("ID_Plat");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 108, 127, 37));

        txt_id_plat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        txt_id_plat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_id_platKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_id_platKeyReleased(evt);
            }
        });
        jPanel5.add(txt_id_plat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 108, 170, 37));

        jLabel6.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel6.setText("Libéllé plat");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 194, 127, 37));

        txt_LibellePlat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        txt_LibellePlat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_LibellePlatKeyPressed(evt);
            }
        });
        jPanel5.add(txt_LibellePlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 194, 170, 37));

        jLabel8.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel8.setText("Date");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 237, 127, 37));

        txt_PrixPlat.setEditable(false);
        txt_PrixPlat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jPanel5.add(txt_PrixPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 280, 170, 37));

        calculerTotalprixPlat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        calculerTotalprixPlat.setText("Calculer total");
        calculerTotalprixPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerTotalprixPlatActionPerformed(evt);
            }
        });
        jPanel5.add(calculerTotalprixPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 366, 137, 33));

        resetcommandPlat.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        resetcommandPlat.setText("Imprimer l'addition");
        resetcommandPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetcommandPlatActionPerformed(evt);
            }
        });
        jPanel5.add(resetcommandPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 494, -1, 33));

        Addcom_plat.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        Addcom_plat.setText("Ajouter à l'addition");
        Addcom_plat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addcom_platActionPerformed(evt);
            }
        });
        jPanel5.add(Addcom_plat, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 455, -1, 33));

        UpdatecommandePlat.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        UpdatecommandePlat.setText("Modifer");
        UpdatecommandePlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatecommandePlatActionPerformed(evt);
            }
        });
        jPanel5.add(UpdatecommandePlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 455, 99, 33));

        DeletecommandePlat.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        DeletecommandePlat.setText("Annuler");
        DeletecommandePlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletecommandePlatActionPerformed(evt);
            }
        });
        jPanel5.add(DeletecommandePlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 494, 96, 33));

        jLabel12.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel12.setText("Type de plat");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 151, 127, 37));

        txt_TypePlat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        txt_TypePlat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrée", "Résistance", "Dessert" }));
        jPanel5.add(txt_TypePlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 151, 170, 37));

        jLabel9.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel9.setText("Nom Client");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 65, 127, 37));

        txt_nom_cli_plat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jPanel5.add(txt_nom_cli_plat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 65, 170, 37));

        jLabel10.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel10.setText("Quantité ");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 323, 127, 37));

        txt_total_prix_plat.setEditable(false);
        txt_total_prix_plat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jPanel5.add(txt_total_prix_plat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 368, 170, 37));

        jLabel17.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel17.setText("Matricule_Client");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 22, 127, 37));

        txtid_cli_plat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        txtid_cli_plat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtid_cli_platKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtid_cli_platKeyReleased(evt);
            }
        });
        jPanel5.add(txtid_cli_plat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 22, 170, 37));

        jLabel18.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel18.setText("Prix du plat");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 280, 127, 37));

        txt_datecommandeplat.setDateFormatString("dd/MM/yyyy");
        txt_datecommandeplat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jPanel5.add(txt_datecommandeplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 237, 170, 35));

        txt_quantite_plat.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        txt_quantite_plat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_quantite_platKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_quantite_platKeyReleased(evt);
            }
        });
        jPanel5.add(txt_quantite_plat, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 323, 170, 37));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.setGridColor(new java.awt.Color(102, 102, 102));
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(51, 255, 102));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable2MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton6.setFont(new java.awt.Font("URW Bookman", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 153));
        jButton6.setIcon(new javax.swing.ImageIcon("/home/prince/Téléchargements/3925426-print-printer-printing-icon_111556.png")); // NOI18N
        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Noto Serif CJK HK Black", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/service/IMAGE/analysis_analytics_magnifier_search_locate_magnifyng_glass_icon_153884.png"))); // NOI18N
        jLabel13.setText("RECHERCHER");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        searchfood.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        searchfood.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchfoodKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchfoodKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(searchfood, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1281, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchfood, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Commande de Plats", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclienIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclienIDKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtclienIDKeyPressed

    private void txtBoissonLibelleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBoissonLibelleKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //  txt_prixUnitaire.requestFocus();
        }
    }//GEN-LAST:event_txtBoissonLibelleKeyPressed

    private void txtquantiteboissonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquantiteboissonKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtquantiteboissonKeyPressed

    private void DeletedrunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletedrunkActionPerformed
        // TODO add your handling code here:
        int ligne = jTable1.getSelectedRow();

        if (ligne < 0 || "".equals(txtclienID.getText()) || "".equals(txtBoissonLibelle.getText()) || "".equals(txtboissonID.getText()) || "".equals(txtquantiteboisson.getText()) || txtdateCommande.getDate() == null) {

            JOptionPane.showMessageDialog(null, "Veuillez sélectionner une ligne du tableau !");
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir supprimer cette donnée ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(jTable1.getValueAt(ligne, 0).toString());

                try {
                    ps = con.prepareStatement("DELETE FROM consommationBoisson WHERE id_cmBoisson = ?");
                    ps.setInt(1, id);
                    ps.executeUpdate();// Pour éxécuter la requête sql.
                    ps = con.prepareStatement("ALTER TABLE consommationBoisson AUTO_INCREMENT = 0;");
                    ps.executeUpdate();

                    JOptionPane.showMessageDialog(null, " Opération effectuée avec succès !!!");
                    TableCommandeBoisson();
                    ResetData();
                    ps.close();
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "" + e.getMessage());
                }
            }

        }
    }//GEN-LAST:event_DeletedrunkActionPerformed

    private void AddDrunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDrunkActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        Date datCmd = txtdateCommande.getDate();
        String myDate = dateFormat.format(datCmd);
        if ("".equals(txtclienID.getText()) || "".equals(txtBoissonLibelle.getText()) || "".equals(txtboissonID.getText()) || "".equals(txtquantiteboisson.getText()) || "".equals(myDate)) {

            JOptionPane.showMessageDialog(null, " Informations Incomplètes ! )");

        } else {

            try {
                ps = con.prepareStatement("INSERT INTO consommationBoisson VALUES (null, ?, ?, ?, ?, ?) ;");

                ps.setString(1, txtclienID.getText());
                ps.setString(2, txtboissonID.getText());
                ps.setString(3, myDate);
                ps.setString(4, txtquantiteboisson.getText());
                ps.setString(5, txtTotalDrunk.getText());

                ps.executeUpdate();
                ps = con.prepareStatement("UPDATE GestionBar SET  quantite = (quantite - ?) WHERE id_bar = ?");
                ps.setString(1, txtquantiteboisson.getText());
                ps.setString(2, txtboissonID.getText());
                ps.executeUpdate();
                ps.close();
                JOptionPane.showMessageDialog(null, " Opération effectuée avec succès !!!");
                TableCommandeBoisson();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

            ResetData();
        }
    }//GEN-LAST:event_AddDrunkActionPerformed

    private void printAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printAdditionActionPerformed
        // TODO add your handling code here:
        ////ResetData();
        int index = jTable1.getSelectedRow();// index stock l'indice de la ligne sélectionné du tableau !!!

        if (index < 0) {
            JOptionPane.showMessageDialog(null, "Veuilez d'abord une ligne du tableau");
        } else {
            int id = Integer.parseInt(jTable1.getValueAt(index, 1).toString());
            try {

                JasperDesign jdesign = JRXmlLoader.load("/home/prince/hotelReports/additonBar.jrxml");
                Map<String, Object> para = new HashMap<String, Object>();
                para.put("id_client", id);
                JasperReport ireport = JasperCompileManager.compileReport(jdesign);
                JasperPrint jPrint = JasperFillManager.fillReport(ireport, para, con);
                JasperViewer.viewReport(jPrint, false);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_printAdditionActionPerformed

    private void UpdatedrunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatedrunkActionPerformed
        // TODO add your handling code here:
        int ligne = jTable1.getSelectedRow();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        if (ligne < 0 || "".equals(txtclienID.getText()) || "".equals(txtBoissonLibelle.getText()) || "".equals(txtboissonID.getText()) || "".equals(txtquantiteboisson.getText()) || txtdateCommande.getDate() == null) {

            JOptionPane.showMessageDialog(null, "Veuillez sélectionner une ligne du tableau !");
        } else {

            int id = Integer.parseInt(jTable1.getValueAt(ligne, 0).toString());
            Date datCmd = txtdateCommande.getDate();
            String myDate = dateFormat.format(datCmd);
            try {
                ps = con.prepareStatement("UPDATE consommationBoisson SET client_id = ?, id_bar = ?, date_commande = ?, quantite_commande = ?, prix_total = ? WHERE id_cmBoisson = ?");
                ps.setString(1, txtclienID.getText());
                ps.setString(2, txtboissonID.getText());
                ps.setString(3, myDate);
                ps.setString(4, txtquantiteboisson.getText());
                ps.setString(5, txtTotalDrunk.getText());
                ps.setInt(6, id);
                ps.executeUpdate();
                ps = con.prepareStatement("UPDATE GestionBar SET  quantite = (quantite - ?) WHERE id_bar = ?");
                ps.setString(1, txtquantiteboisson.getText());
                ps.setString(2, txtboissonID.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, " Opération effectuée avec succès !!!");
                TableCommandeBoisson();
                ResetData();
                ps.close();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_UpdatedrunkActionPerformed

    private void totacmdDrunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totacmdDrunkActionPerformed
        // TODO add your handling code here:
        double prix_cmdDrunk = Double.parseDouble(txtPU.getText());
        double qteDrunk = Double.parseDouble(txtquantiteboisson.getText());
        double totalDrunk = prix_cmdDrunk * qteDrunk;
        txtTotalDrunk.setText("" + totalDrunk);
    }//GEN-LAST:event_totacmdDrunkActionPerformed

    private void txtnomclientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomclientKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomclientKeyPressed

    private void txtboissonIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtboissonIDKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtboissonIDKeyPressed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        try {
            // TODO add your handling code here:
            int index = jTable1.getSelectedRow();// index stock l'indice de la ligne sélectionné du tableau !!!
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            txtclienID.setText(m.getValueAt(index, 1).toString());
            txtnomclient.setText(m.getValueAt(index, 2).toString());
            txtboissonID.setText(m.getValueAt(index, 3).toString());
            SimpleDateFormat dateformat = new SimpleDateFormat("dd/MM/yyy");
            Date date_cmd = dateformat.parse(jTable1.getValueAt(index, 4).toString());
            txtdateCommande.setDate(date_cmd);

            txtquantiteboisson.setText(m.getValueAt(index, 5).toString());
            txtTotalDrunk.setText(m.getValueAt(index, 6).toString());

            int id_cli = Integer.parseInt(jTable1.getValueAt(index, 1).toString());
            int id_Drunk = Integer.parseInt(jTable1.getValueAt(index, 3).toString());
            try {
                ps = con.prepareStatement("SELECT typeBoisson, libelleBoisson, prixBoisson FROM GestionBar WHERE id_bar = ?;");
                ps.setInt(1, id_Drunk);
                rs = ps.executeQuery();
                while (rs.next()) {
                    txtcategorie.setSelectedItem(rs.getString("typeBoisson"));
                    txtBoissonLibelle.setText(rs.getString("libelleBoisson"));
                    txtPU.setText(rs.getString("prixBoisson"));
                }
                ps.close();
                // rs.close();
//                ps = con.prepareStatement("SELECT nom FROM clients WHERE client_id = ?;");
//                ps.setInt(1, id_cli);
//                rs = ps.executeQuery();
//                while (rs.next()) {
//                    txtnomclient.setText(rs.getString("nom"));
//                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } catch (ParseException ex) {
            Logger.getLogger(Consommaton.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat(" \n Liste des commandes: \n");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.PORTRAIT);
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, set, true);
            JOptionPane.showMessageDialog(null, "\n Printed successfully !");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "\n Erreur d'impression \n" + e.getMessage());
            e.printStackTrace();

        }

//        try {
//            JasperDesign jdesign = JRXmlLoader.load("/home/prince/liste_chambre.jrxml");
//            JasperReport ireport = JasperCompileManager.compileReport(jdesign);
//            JasperPrint jPrint = JasperFillManager.fillReport(ireport, null, con);
//            JasperViewer.viewReport(jPrint);
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, e);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcmdDrunkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcmdDrunkKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtcmdDrunkKeyPressed

    private void txt_id_platKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_platKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_platKeyPressed

    private void txt_id_platKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_platKeyReleased
        // TODO add your handling code here:
        try {
            ps = con.prepareStatement("SELECT typePlat, libellePlat, prixPlat FROM GestionRestaurant WHERE id_plat = ?;");
            ps.setString(1, txt_id_plat.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                txt_TypePlat.setSelectedItem(rs.getString("typePlat"));
                txt_LibellePlat.setText(rs.getString("libellePlat"));
                txt_PrixPlat.setText(rs.getString("prixPlat"));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txt_id_platKeyReleased

    private void txt_LibellePlatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_LibellePlatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_PrixPlat.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LibellePlatKeyPressed

    private void calculerTotalprixPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerTotalprixPlatActionPerformed
        // TODO add your handling code here:
        int qte_plat = Integer.parseInt(txt_quantite_plat.getText());
        double price_food = Double.parseDouble(txt_PrixPlat.getText());
        double totalprice = price_food * (double) qte_plat;
        txt_total_prix_plat.setText("" + totalprice);
    }//GEN-LAST:event_calculerTotalprixPlatActionPerformed

    private void resetcommandPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetcommandPlatActionPerformed
        // TODO add your handling code here:
        int index = jTable2.getSelectedRow();// index stock l'indice de la ligne sélectionné du tableau !!!

        if (index < 0) {
            JOptionPane.showMessageDialog(null, "Veuilez d'abord une ligne du tableau");
        } else {
            int id = Integer.parseInt(jTable2.getValueAt(index, 1).toString());
            try {

                JasperDesign jdesign = JRXmlLoader.load("/home/prince/hotelReports/additionResto.jrxml");
                Map<String, Object> para = new HashMap<String, Object>();
                para.put("id_client", id);
                JasperReport ireport = JasperCompileManager.compileReport(jdesign);
                JasperPrint jPrint = JasperFillManager.fillReport(ireport, para, con);
                JasperViewer.viewReport(jPrint, false);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_resetcommandPlatActionPerformed

    private void Addcom_platActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addcom_platActionPerformed
        // TODO add your handling code here:
        String codePlat = txt_id_plat.getText();
        String LibellePlat = txt_LibellePlat.getText();
        String price = txt_PrixPlat.getText();
        String cli_id = txtid_cli_plat.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        Date datCmd = txt_datecommandeplat.getDate();
        String myDate = dateFormat.format(datCmd);

        if ("".equals(codePlat) || "".equals(LibellePlat) || "".equals(price) || "".equals(cli_id) || datCmd == null) {
            JOptionPane.showMessageDialog(null, "Informations incomplètes !!!");
        } else {
            try {
                ps = con.prepareStatement("INSERT INTO consommationPlat VALUES (null, ?, ?, ?, ?, ?) ;");

                ps.setString(1, txtid_cli_plat.getText());
                ps.setString(2, txt_id_plat.getText());
                ps.setString(3, myDate);
                ps.setString(4, txt_quantite_plat.getText());
                ps.setString(5, txt_total_prix_plat.getText());
                ps.executeUpdate();

                ps.close();
                JOptionPane.showMessageDialog(null, " Opération effectuée avec succès !!!");
                TablePlatCommande();
                ResetFoodDataCommande();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_Addcom_platActionPerformed

    private void UpdatecommandePlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatecommandePlatActionPerformed
        // TODO add your handling code here:
        int line = jTable2.getSelectedRow();

        String codePlat = txt_id_plat.getText();
        String LibellePlat = txt_LibellePlat.getText();
        String price = txt_PrixPlat.getText();
        String cli_id = txtid_cli_plat.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        if (line < 0 || "".equals(codePlat) || "".equals(LibellePlat) || "".equals(price) || "".equals(cli_id) || txt_datecommandeplat.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Veuillez d'abord sélectionner une ligne du tableau !!!");
        } else {
            Date datCmd = txt_datecommandeplat.getDate();
            int id = Integer.parseInt(jTable2.getValueAt(line, 0).toString());
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String date_cmd;
                date_cmd = sdf.format(txt_datecommandeplat.getDate());

                ps = con.prepareStatement("UPDATE consommationPlat SET client_id = ?, id_plat = ?, date_commande = ? quantite_plat = ?, prix_total = ? WHERE id_cmplat = ?;");
                for (int i = 1; i < 7; i++) {
                    ps.setString(i, txtid_cli_plat.getText());
                    ps.setString(i, txt_id_plat.getText());
                    ps.setString(i, date_cmd);
                    ps.setString(i, txt_quantite_plat.getText());
                    ps.setString(i, txt_total_prix_plat.getText());

                    ps.setInt(i, id);
                }

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Modification effectuée avec succès !!!");
                TablePlatCommande();
                ResetFoodDataCommande();

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_UpdatecommandePlatActionPerformed

    private void DeletecommandePlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletecommandePlatActionPerformed
        // TODO add your handling code here:
        ResetFoodDataCommande();
        /*  int line = jTable2.getSelectedRow();
        int id = Integer.parseInt(jTable2.getValueAt(line, 0).toString());
        if (id < 0) {
            JOptionPane.showMessageDialog(null, "Veuillez d'abord sélectionner un plat !!!");
        } else {
            try {
                ps = con.prepareStatement("DELETE * FROM GestionBar WHERE id_plat = ?;");
                ps.setInt(1, id);
                ps.executeUpdate();
                ps = con.prepareStatement("ALTER TABLE GestionBar AUTO_INCREMENT = 0;");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Opération effectuée avecsuccès !!!");
                TablePlatCommande();
                ResetFoodDataCommande();

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }*/
    }//GEN-LAST:event_DeletecommandePlatActionPerformed

    private void txtid_cli_platKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtid_cli_platKeyPressed
        // TODO add your handling code here:
        try {
            ps = con.prepareStatement("SELECT nom FROM clients WHERE client_id = ?;");
            ps.setString(1, txtid_cli_plat.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                txt_nom_cli_plat.setText(rs.getString("nom"));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txtid_cli_platKeyPressed

    private void txtid_cli_platKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtid_cli_platKeyReleased
        // TODO add your handling code here:

        try {
            ps = con.prepareStatement("SELECT nom FROM clients WHERE client_id = ?;");
            ps.setString(1, txtid_cli_plat.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                txt_nom_cli_plat.setText(rs.getString("nom"));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txtid_cli_platKeyReleased

    private void txt_quantite_platKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantite_platKeyPressed
        // TODO add your handling code here:
        /*
        int qte_plat = Integer.parseInt(txt_quantite_plat.getText());
        double price_food = Double.parseDouble(txt_PrixPlat.getText());
        double totalprice = price_food * (double) qte_plat;
        txt_total_prix_plat.setText("" + totalprice);
         */
    }//GEN-LAST:event_txt_quantite_platKeyPressed

    private void txt_quantite_platKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantite_platKeyReleased
        // TODO add your handling code here:

        int qte_plat = Integer.parseInt(txt_quantite_plat.getText());
        double price_food = Double.parseDouble(txt_PrixPlat.getText());
        double totalprice = price_food * (double) qte_plat;
        txt_total_prix_plat.setText("" + totalprice);
    }//GEN-LAST:event_txt_quantite_platKeyReleased

    private void jTable2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseReleased
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            int index = jTable2.getSelectedRow();// index stock l'indice de la ligne sélectionné du tableau !!!
            DefaultTableModel m = (DefaultTableModel) jTable2.getModel();
            txtid_cli_plat.setText(m.getValueAt(index, 1).toString());
            txt_nom_cli_plat.setText(m.getValueAt(index, 2).toString());
            txt_id_plat.setText(m.getValueAt(index, 3).toString());
            SimpleDateFormat dateformat = new SimpleDateFormat("dd/MM/yyy");// objet de format de Date 
            Date date_cmd = dateformat.parse(jTable2.getValueAt(index, 4).toString());// récuperer la date dans le Tableau et la convertir en type Date
            txt_datecommandeplat.setDate(date_cmd); // Ensuite afficher la date dans le jDateChooser

            txt_quantite_plat.setText(m.getValueAt(index, 5).toString());
            txt_total_prix_plat.setText(m.getValueAt(index, 6).toString());

            int id_cli = Integer.parseInt(jTable2.getValueAt(index, 1).toString());
            int id_food = Integer.parseInt(jTable2.getValueAt(index, 3).toString());
            try {
                ps = con.prepareStatement("SELECT typePlat, libellePlat, prixPlat FROM GestionRestaurant WHERE id_plat = ?;");
                ps.setInt(1, id_food);
                rs = ps.executeQuery();
                while (rs.next()) {
                    txt_TypePlat.setSelectedItem(rs.getString("typePlat"));
                    txt_LibellePlat.setText(rs.getString("libellePlat"));
                    txt_PrixPlat.setText(rs.getString("prixPlat"));
                }
                ps.close();
                // rs.close();
                ps = con.prepareStatement("SELECT nom FROM clients WHERE client_id = ?;");
                ps.setInt(1, id_cli);
                rs = ps.executeQuery();
                while (rs.next()) {
                    txt_nom_cli_plat.setText(rs.getString("nom"));
                }
                ps.close();

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } catch (ParseException ex) {
            Logger.getLogger(Consommaton.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTable2MouseReleased

    private void searchfoodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfoodKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchfoodKeyPressed

    private void txtBoissonLibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoissonLibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoissonLibelleActionPerformed

    private void txtquantiteboissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantiteboissonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantiteboissonActionPerformed

    private void txtcmdDrunkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcmdDrunkKeyReleased
        // TODO add your handling code here:
        TableSearchDrunkcmd();
    }//GEN-LAST:event_txtcmdDrunkKeyReleased

    private void searchfoodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfoodKeyReleased
        // TODO add your handling code here:
        TableResultFood();
    }//GEN-LAST:event_searchfoodKeyReleased

    private void txtclienIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclienIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclienIDActionPerformed

    private void txtclienIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclienIDKeyReleased
        // TODO add your handling code here:
        String id_cli = txtclienID.getText();
        try {
            ps = con.prepareStatement("SELECT nom FROM clients WHERE client_id = ? ;");
            ps.setString(1, id_cli);
            rs = ps.executeQuery();
            while (rs.next()) {
                String name = rs.getString("nom");
                txtnomclient.setText(name);

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txtclienIDKeyReleased

    private void txtboissonIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtboissonIDKeyReleased
        // TODO add your handling code here:
        String id_drunk = txtboissonID.getText();
        try {
            ps = con.prepareStatement("SELECT typeBoisson, libelleBoisson, prixBoisson FROM GestionBar WHERE id_bar = ?");
            ps.setString(1, id_drunk);
            rs = ps.executeQuery();
            while (rs.next()) {
                txtcategorie.setSelectedItem(rs.getString("typeBoisson"));
                txtBoissonLibelle.setText(rs.getString("libelleBoisson"));
                txtPU.setText(rs.getString("prixBoisson"));

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txtboissonIDKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat(" \n Liste des Commandes de plats: \n");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.PORTRAIT);
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, set, true);
            JOptionPane.showMessageDialog(null, "\n Printed successfully !");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "\n Erreur d'impression \n" + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtquantiteboissonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquantiteboissonKeyReleased
        // TODO add your handling code here:
        double prix_cmdDrunk = Double.parseDouble(txtPU.getText());
        String qteDrunkString = txtquantiteboisson.getText();
        double qteDrunk;

        if (!qteDrunkString.isEmpty()) {
            qteDrunk = Double.parseDouble(qteDrunkString);
            double totalDrunk = prix_cmdDrunk * qteDrunk;
            txtTotalDrunk.setText("" + totalDrunk);
        } else {
            JOptionPane.showMessageDialog(null, "Veuillez saisir une quantité.");
        }
    }//GEN-LAST:event_txtquantiteboissonKeyReleased

    private void ResetCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetCommandActionPerformed
        // TODO add your handling code here:
        ResetData();
    }//GEN-LAST:event_ResetCommandActionPerformed
    public void ResetData() {

        txtclienID.setText("");
        txtnomclient.setText("");
        txtboissonID.setText("");
        txtcategorie.setSelectedItem(null);
        txtBoissonLibelle.setText("");
        txtdateCommande.setDate(null);
        txtPU.setText("");
        txtTotalDrunk.setText("");
        txtquantiteboisson.setText("");

    }

    public void ResetFoodDataCommande() {
        txt_id_plat.setText("");
        txt_TypePlat.setSelectedItem(null);
        txt_LibellePlat.setText("");
        txt_PrixPlat.setText("");
        txtid_cli_plat.setText("");
        txt_nom_cli_plat.setText("");
        txt_total_prix_plat.setText("");
        txt_quantite_plat.setText("");
        txt_datecommandeplat.setDate(null);

    }

    public void TableCommandeBoisson() {
        String[] Commande = {"N°_commande", "Matricule_Client", "Nom ", "ID_Boisson", "Date_commande", "Quantité", "Total"};
        String[] afficher = new String[8];
        DefaultTableModel mod = new DefaultTableModel(null, Commande);

        try {

            Statement st = con.createStatement();// variable statement pour intéragir avec la base de donées !!!

            rs = st.executeQuery("SELECT * FROM consommationBoisson INNER JOIN clients ON clients.client_id = consommationBoisson.client_id ;");// on stocke le résultat de la requête dans le resultStatement
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String date_cmd;
            while (rs.next()) {
                afficher[0] = rs.getString("id_cmBoisson");
                afficher[1] = rs.getString("client_id");
                afficher[2] = rs.getString("nom");
                afficher[3] = rs.getString("id_bar");
                date_cmd = sdf.format(rs.getDate("date_commande"));
                afficher[4] = date_cmd;
                afficher[5] = rs.getString("quantite_commande");
                afficher[6] = rs.getString("prix_total");

                mod.addRow(afficher);
            }

            jTable1.setModel(mod);
            //con.close();

        } catch (Exception e) {
            e.printStackTrace();// Affiche l'erreur retourné dans le terminal si le try n'a pas pu être éxécuté 
            JOptionPane.showMessageDialog(null, " " + e.getMessage());
        }
    }

    public void TableSearchDrunkcmd() {
        String[] Commande = {"N°_commande", "Matricule_Client", "Nom ", "ID_Boisson", "Date_commande", "Quantité", "Total"};
        String[] afficher = new String[8];
        DefaultTableModel mod = new DefaultTableModel(null, Commande);
        String resultcmdDrunk = txtcmdDrunk.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String date_cmd;
        String myDate = "";
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        try {

            ps = con.prepareStatement("SELECT * FROM consommationBoisson INNER JOIN clients ON clients.client_id = consommationBoisson.client_id WHERE (nom LIKE ?) OR (date_commande LIKE ?) OR (quantite_commande LIKE ?) OR (prix_total LIKE ?);");// on stocke le résultat de la requête dans le resultStatement
            for (int i = 1; i < 5; i++) {
                ps.setString(i, "%" + resultcmdDrunk + "%");
            }
            if (resultcmdDrunk.indexOf("/") != -1) {
                Date datCmd = sdf.parse(resultcmdDrunk);
                myDate = dateFormat.format(datCmd);
                ps.setString(2, "%" + myDate + "%");
            }

            rs = ps.executeQuery();
            while (rs.next()) {
                afficher[0] = rs.getString("id_cmBoisson");
                afficher[1] = rs.getString("client_id");
                afficher[2] = rs.getString("nom");
                afficher[3] = rs.getString("id_bar");
                date_cmd = sdf.format(rs.getDate("date_commande"));
                afficher[4] = date_cmd;
                afficher[5] = rs.getString("quantite_commande");
                afficher[6] = rs.getString("prix_total");

                mod.addRow(afficher);
            }

            jTable1.setModel(mod);
            //con.close();

        } catch (SQLException e) {
            e.printStackTrace();// Affiche l'erreur retourné dans le terminal si le try n'a pas pu être éxécuté 
            JOptionPane.showMessageDialog(null, " " + e.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(Consommaton.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }

    public void TablePlatCommande() {
        String[] consommationPlat = {"N°", "Matricule_Client", "nom", "ID_Plat", "Date_commande", "Quantité de plat", "Total"};
        String[] afficher = new String[8];
        DefaultTableModel mod = new DefaultTableModel(null, consommationPlat);

        try {

            Statement st = con.createStatement();// variable statement pour intéragir avec la base de donées !!!

            rs = st.executeQuery("SELECT * FROM consommationPlat INNER JOIN clients ON clients.client_id = consommationPlat.client_id;");// on stocke le résultat de la requête dans le resultStatement
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String date_cmd;
            while (rs.next()) {
                afficher[0] = rs.getString("id_cmplat");
                afficher[1] = rs.getString("client_id");
                afficher[2] = rs.getString("nom");
                afficher[3] = rs.getString("id_plat");
                date_cmd = sdf.format(rs.getDate("date_commande"));
                afficher[4] = date_cmd;
                afficher[5] = rs.getString("quantite_plat");
                afficher[6] = rs.getString("prix_total");

                mod.addRow(afficher);
            }

            jTable2.setModel(mod);

        } catch (SQLException e) {
            e.printStackTrace();// Affiche l'erreur retourné dans le terminal si le try n'a pas pu être éxécuté 
            JOptionPane.showMessageDialog(null, " " + e.getMessage());
        }
    }

    public void TableResultFood() {
        String[] GestionRestaurant = {"N°", "Matricule_Client", "nom", "ID_Plat", "Date_commande", "Quantité de plat", "Total"};
        String[] afficher = new String[8];
        DefaultTableModel mod = new DefaultTableModel(null, GestionRestaurant);
        String researchFood = searchfood.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String date_cmd;
        String myDate = "";
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date datCmd;
        try {

            ps = con.prepareStatement("SELECT * FROM consommationPlat INNER JOIN clients ON clients.client_id = consommationPlat.client_id WHERE (nom LIKE ?) OR (typePlat LIKE ?) OR (libellePlat LIKE ?) OR (date_commande LIKE ?) OR (quantite_plat LIKE ?) OR (prix_total LIKE ?);");// on stocke le résultat de la requête dans le resultStatement
            for (int i = 1; i < 7; i++) {
                ps.setString(i, "%" + researchFood + "%");
            }

            if (researchFood.indexOf("/") != -1) {

                datCmd = sdf.parse(researchFood);
                myDate = dateFormat.format(datCmd);
                ps.setString(4, "%" + myDate + "%");

            }

            while (rs.next()) {
                afficher[0] = rs.getString("id_cmplat");
                afficher[1] = rs.getString("client_id");
                afficher[2] = rs.getString("nom");
                afficher[3] = rs.getString("id_plat");
                date_cmd = sdf.format(rs.getDate("date_commande"));
                afficher[4] = date_cmd;
                afficher[5] = rs.getString("quantite_plat");
                afficher[6] = rs.getString("prix_total");

                mod.addRow(afficher);
            }

            jTable2.setModel(mod);

        } catch (SQLException e) {
            e.printStackTrace();// Affiche l'erreur retourné dans le terminal si le try n'a pas pu être éxécuté 
            JOptionPane.showMessageDialog(null, " " + e.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(Consommations.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDrunk;
    private javax.swing.JButton Addcom_plat;
    private javax.swing.JButton DeletecommandePlat;
    private javax.swing.JButton Deletedrunk;
    private javax.swing.JButton ResetCommand;
    private javax.swing.JButton UpdatecommandePlat;
    private javax.swing.JButton Updatedrunk;
    private javax.swing.JButton calculerTotalprixPlat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton printAddition;
    private javax.swing.JButton resetcommandPlat;
    private javax.swing.JTextField searchfood;
    private javax.swing.JButton totacmdDrunk;
    private javax.swing.JTextField txtBoissonLibelle;
    private javax.swing.JTextField txtPU;
    private javax.swing.JTextField txtTotalDrunk;
    private javax.swing.JTextField txt_LibellePlat;
    private javax.swing.JTextField txt_PrixPlat;
    private javax.swing.JComboBox<String> txt_TypePlat;
    private com.toedter.calendar.JDateChooser txt_datecommandeplat;
    private javax.swing.JTextField txt_id_plat;
    private javax.swing.JTextField txt_nom_cli_plat;
    private javax.swing.JTextField txt_quantite_plat;
    private javax.swing.JTextField txt_total_prix_plat;
    private javax.swing.JTextField txtboissonID;
    private javax.swing.JComboBox<String> txtcategorie;
    private javax.swing.JTextField txtclienID;
    private javax.swing.JTextField txtcmdDrunk;
    private com.toedter.calendar.JDateChooser txtdateCommande;
    private javax.swing.JTextField txtid_cli_plat;
    private javax.swing.JTextField txtnomclient;
    private javax.swing.JTextField txtquantiteboisson;
    // End of variables declaration//GEN-END:variables
}
